# Generated by Django 5.1.7 on 2025-06-10 17:33

import baseApp.models
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='NP', validators=[baseApp.models.validate_phone]),
        ),
    ]
