# Generated by Django 5.1.7 on 2025-06-10 17:36

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ok',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='male', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
