# Generated by Django 5.1.7 on 2025-06-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_city_interest_alter_student_ok_person_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseApp.city'),
        ),
    ]
