# Generated by Django 5.1.7 on 2025-06-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_person_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, default='no city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseApp.city'),
        ),
    ]
